name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd mdviewer
          swift build -c release -Xswiftc -warnings-as-errors -v

      - name: Test
        run: |
          cd mdviewer
          swift test -Xswiftc -warnings-as-errors -v
